server:
  port: 8082


dubbo:
    application:
      name: dubbo-provider
    registry:
      address: zookeeper://127.0.0.1:2181
      protocol: zookeeper
      check: false
    protocol:
      name: dubbo
      port: 30003
    monitor:
      protocol: register
    consumer:
      check: false
      timeout: 3000